apiVersion: v1
kind: Secret
metadata:
  name: justjio-api-secret
type: Opaque
data:
  # DSN: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
  DSN: ${DSN}
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  VAPID_EMAIL: ${ADMIN_EMAIL}
  VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
  VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
  SMTP2GO_API_KEY: ${SMTP2GO_API_KEY}
  JWT_SECRET: ${JWT_SECRET}
  KAFKA_URL: ${KAFKA_HOST}:${KAFKA_PORT}
