apiVersion: v1
kind: Service
metadata:
  namespace: justjio
  name: justjio-ws-service
spec:
  selector:
    app: justjio-ws
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
