name: justjio-dev

x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 5

services:
  frontend:
    profiles:
      - full
    image: ghcr.io/rowentey/justjio/web:latest
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      APP_ENV_PREFIX: VITE
      VITE_API_URL: http://localhost:8080/v1
      VITE_WS_URL: ws://localhost:8081
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      VITE_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VITE_ENV: dev
      VITE_CF_ACCESS_CLIENT_ID: ${CF_ACCESS_CLIENT_ID}
      VITE_CF_ACCESS_CLIENT_SECRET: ${CF_ACCESS_CLIENT_SECRET}
    depends_on:
      - api-server
      - ws-server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      <<: *common-healthcheck

  api-server:
    profiles:
      - full
    image: ghcr.io/rowentey/justjio/api:latest
    build:
      context: ../../server/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NUv5oMuh1EWV
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_TOPIC_PREFIX: justjio
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      GOOGLE_REDIRECT_URL: http://localhost:80
      VAPID_EMAIL: ${ADMIN_EMAIL}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      SMTP2GO_API_KEY: ${SMTP2GO_API_KEY}
      ALLOWED_ORIGINS: http://localhost:80
    entrypoint: ["/api-server", "staging"]
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      <<: *common-healthcheck

  ws-server:
    profiles:
      - full
    image: ghcr.io/rowentey/justjio/ws:latest
    build:
      context: ../../server/ws
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_TOPIC_PREFIX: justjio
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      ALLOWED_ORIGINS: http://localhost:80
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/ping || exit 1"]
      <<: *common-healthcheck
      
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_KRAFT_MODE: "true" 
      KAFKA_PROCESS_ROLES: controller,broker 
      KAFKA_NODE_ID: 1 
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093" 
      KAFKA_LISTENERS: INNER://kafka:29092,PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INNER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: INNER://kafka:29092,PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk" 
    volumes:
      - justjio-kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      PG_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NUv5oMuh1EWV
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - justjio-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      <<: *common-healthcheck

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    user: root
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    volumes:
      - ./config/pgadmin/pgpass:/pgpass
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres

volumes:
  justjio-postgres-data:
  justjio-kafka-data:
