name: justjio-staging

x-common-env: &common-env
  JWT_SECRET: ${JWT_SECRET}
  KAFKA_HOST: ${KAFKA_HOST}
  KAFKA_PORT: ${KAFKA_PORT}
  KAFKA_TOPIC_PREFIX: justjio
  ALLOWED_ORIGINS: https://justjio-staging.rowentey.xyz

x-common-config: &common-config
  restart: unless-stopped
  networks:
    - justjio_network
    - cloudflare_network
    
x-common-healthcheck: &common-healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  
services:
  frontend:
    container_name: justjio-web
    image: ghcr.io/rowentey/justjio/web:latest
    <<: *common-config
    environment:
      APP_ENV_PREFIX: VITE
      VITE_API_URL: https://justjio-api-staging.rowentey.xyz/v1
      VITE_WS_URL: wss://justjio-ws-staging.rowentey.xyz
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      VITE_VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VITE_ENV: staging
      VITE_CF_ACCESS_CLIENT_ID: ${CF_ACCESS_CLIENT_ID}
      VITE_CF_ACCESS_CLIENT_SECRET: ${CF_ACCESS_CLIENT_SECRET}
    depends_on:
      - api-server
      - ws-server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      <<: *common-healthcheck

  api-server:
    container_name: justjio-api
    image: ghcr.io/rowentey/justjio/api:latest
    <<: *common-config
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: 8080
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      GOOGLE_REDIRECT_URL: https://justjio-staging.rowentey.xyz
      VAPID_EMAIL: ${ADMIN_EMAIL}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      SMTP2GO_API_KEY: ${SMTP2GO_API_KEY}
      <<: *common-env
    entrypoint: ["/api-server", "staging"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      <<: *common-healthcheck

  ws-server:
    container_name: justjio-ws
    image: ghcr.io/rowentey/justjio/ws:latest
    <<: *common-config
    environment:
      PORT: 8081
      <<: *common-env
    entrypoint: ["/ws-server", "staging"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/ping || exit 1"]
      <<: *common-healthcheck

networks:
  justjio_network:
    name: justjio_network
  cloudflare_network:
    external: true
