apiVersion: v1
kind: Service
metadata:
  namespace: justjio
  name: justjio-web-service
spec:
  selector:
    app: justjio-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
