name: CI Pipeline to build Docker Images

on:
  pull_request:
    types: [labeled]
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-images:
    if: ${{ github.event.label.name == 'ready_for_build' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            { name: api, directory: server-api },
            { name: ws, directory: server-ws },
            { name: web, directory: client-web },
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.service.name }}
          tags: |
            type=sha
            latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./${{ matrix.service.directory }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Remove `ready_for_build` label
        if: always() && github.event_name != 'workflow_dispatch'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ready_for_build

  add-ready-to-merge-label:
    if: ${{ github.event.label.name == 'ready_for_build' }}
    needs: [build-and-push-images]
    runs-on: ubuntu-latest
    steps:
      - name: Remove `ready_for_build` label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github-token: ${{ secrets.PAT }}
          labels: ready_for_build

      - name: Add `ready_to_merge` label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github-token: ${{ secrets.PAT }}
          labels: ready_to_merge
