name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  lint-and-format-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Lint React code
        run: npm run lint
        working-directory: ./client

      - name: Format React code
        run: npm run format
        working-directory: ./client

      - name: Check for changes
        id: git-check-react
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check-react.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "style: Formatted code with prettier"

      - name: Push changes
        if: steps.git-check-react.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

  lint-and-format-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ["./server/api", "./server/ws"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: |
            ${{ matrix.modules }}/go.sum

      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=10m
          version: v1.60
          working-directory: ${{ matrix.modules }}

      - name: Format Go code
        run: |
          gofmt -s -w ${{ matrix.modules }}

      - name: Check for changes
        id: git-check-go
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check-go.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "style: Formatted code with go formatter"

      - name: Push changes
        if: steps.git-check-go.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

  build-go-app:
    runs-on: ubuntu-latest
    needs: [lint-and-format-go, lint-and-format-react]
    strategy:
      matrix:
        modules: ["./server/api", "./server/ws"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: |
            ${{ matrix.modules }}/go.sum

      - name: Build Go app
        run: go build -v ./...
        working-directory: ${{ matrix.modules }}

  test-api-server:
    runs-on: ubuntu-latest
    needs: [build-go-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
          cache-dependency-path: ./server/api/go.sum

      - name: Install dependencies
        run: cd ./server/api && go mod download

      - name: Run unit tests with coverage
        run: |
          cd ./server/api
          go test -coverprofile=coverage.out -covermode=atomic -v ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./server/api/coverage.out

  run-security-scan:
    runs-on: ubuntu-latest
    needs: [test-api-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "HIGH,CRITICAL"
          exit-code: 0

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      # display table and fail if severity detected
      - name: Display vulnerability table
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          severity: "HIGH,CRITICAL"
          exit-code: 1
          # skip setting up trivy
          skip-setup-trivy: true
        env:
          # skip updating the database on 2nd run
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true
          # unset the output format
          TRIVY_FORMAT:
          TRIVY_OUTPUT:
          TRIVY_DEBUG: true

  run-sonarqube-scan:
    runs-on: ubuntu-latest
    needs: [test-api-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: server/api/

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Check the Quality Gate status
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Display output from the Quality Gate
      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`
      - name: "Example show SonarQube Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
