name: Deploy to Production Environment

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://justjio.rowentey.xyz/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # only checkout k8s files
          sparse-checkout: |
            infra/k8s
          sparse-checkout-cone-mode: false

      - name: Prepare k8s secret
        run: |
          export DSN=$(echo -n "postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@${{ vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DB }}?sslmode=disable" | base64 -w 0)
          export JWT_SECRET=$(echo -n "${{ secrets.JWT_SECRET }}" | base64 -w 0)
          export ADMIN_EMAIL=$(echo -n "${{ secrets.ADMIN_EMAIL }}" | base64 -w 0)
          export KAFKA_URL=$(echo -n "${{ vars.KAFKA_HOST }}:${{ vars.KAFKA_PORT }}" | base64 -w 0)
          export GOOGLE_CLIENT_ID=$(echo -n "${{ secrets.GOOGLE_CLIENT_ID }}" | base64 -w 0)
          export GOOGLE_CLIENT_SECRET=$(echo -n "${{ secrets.GOOGLE_CLIENT_SECRET }}" | base64 -w 0)
          export VAPID_EMAIL=$(echo -n "${{ secrets.ADMIN_EMAIL }}" | base64 -w 0)
          export VAPID_PUBLIC_KEY=$(echo -n "${{ secrets.VAPID_PUBLIC_KEY }}" | base64 -w 0)
          export VAPID_PRIVATE_KEY=$(echo -n "${{ secrets.VAPID_PRIVATE_KEY }}" | base64 -w 0)
          export SMTP2GO_API_KEY=$(echo -n "${{ secrets.SMTP2GO_API_KEY }}" | base64 -w 0)
          export CF_ACCESS_CLIENT_ID=$(echo -n "${{ secrets.CF_ACCESS_CLIENT_ID }}" | base64 -w 0)
          export CF_ACCESS_CLIENT_SECRET=$(echo -n "${{ secrets.CF_ACCESS_CLIENT_SECRET }}" | base64 -w 0)

          find infra/k8s/ -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
            echo "Processing $dir"
            if [[ -f "$dir/secrets.template.yaml" ]]; then
              echo "Processing $dir/secret-template.yaml"

              # Substitute env vars and generate secrets.yaml
              envsubst < "$dir/secrets.template.yaml" > "$dir/secrets.yaml"
              echo "Generated $dir/secrets.yaml"
              
              # Remove the template file
              rm "$dir/secrets.template.yaml"
            fi
          done

      # Transfer files to the server
      - name: Transfer files to pruduction server
        uses: RowenTey/cloudflared-scp-action@v1.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          port: ${{ secrets.SSH_PORT }}
          from: |
            ./infra/k8s
          to: ${{ vars.PROD_DIR }}/
          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}

      - name: Deploy on production server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
          port: ${{ secrets.SSH_PORT }}
          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
          commands: |
            cd ${{ vars.PROD_DIR }}
            export KUBECONFIG=~/.kube/config
            kubectl apply -f k8s/ --recursive
