name: Run Security Scan

on:
  workflow_run:
    workflows: [Run Unit Tests]
    types:
      - completed
  workflow_dispatch:

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      # get SHA of PR from the workflow that triggered this one
      - name: Download workflow data
        if: ${{ github.event.workflow_run != null }}
        id: download-sha
        uses: dawidd6/action-download-artifact@v9
        with:
          name: pr-head-sha
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success

      - name: Get head SHA
        if: ${{ github.event.workflow_run != null && success() }}
        id: get-sha
        run: echo "HEAD_SHA=$(cat head_sha.txt)" >> $GITHUB_OUTPUT

      # custom script to create a check run
      - name: Create check
        if: ${{ github.event.workflow_run != null && success() }}
        id: create-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the head_sha from the workflow that triggered this one
            const headSha = ${{ steps.get-sha.outputs.HEAD_SHA }};

            const { data: checkRun } = await github.rest.checks.create({
              name: 'trivy-security-scan',
              head_sha: headSha,
              status: 'in_progress',
              details_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,  
              external_id: `${context.runId}`,           
              started_at: new Date().toISOString(),
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('check_run_id', checkRun.id);
            console.log("Created check");

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        id: trivy-scan-step
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"
          exit-code: "1"

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ github.event.workflow_run != null && steps.trivy-scan-step.outcome != null }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      # custom script to report scan results
      - name: Report scan results
        if: ${{ github.event.workflow_run != null && steps.trivy-scan-step.outcome != null }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const conclusion = '${{ steps.trivy-scan-step.outcome }}';

            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.create-check.outputs.check_run_id }},
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'Trivy Security Scan Results',
                summary: `Scan completed with conclusion: ${conclusion}`
              },
              completed_at: new Date().toISOString(),
            });
            console.log("Updated check with conclusion: " + conclusion);
