name: Run Security Scan

on:
  pull_request:
    types: [labeled]
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'ready_for_scan' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # display table
      - name: Display vulnerability table
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          severity: "HIGH,CRITICAL"

      - name: Run Trivy vulnerability scanner in repo mode
        id: trivy-scan-step
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "HIGH,CRITICAL"
          exit-code: "1"

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  remove-ready-for-scan-label:
    if: always() && ${{ github.event.label.name == 'ready_for_scan' }}
    needs: [security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Remove `ready_for_scan` label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.PAT }}
          labels: ready_for_scan