name: Run Security Scan

on:
  workflow_run:
    workflows: [Run Unit Tests]
    types:
      - completed
  workflow_dispatch:

jobs:
  run-security-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      # custom script to create a check run
      - name: Create check
        if: ${{ github.event.workflow_run != null }}
        id: create-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the head_sha from the workflow that triggered this one
            const headSha = context.payload.workflow_run.head_sha;

            const { data: checkRun } = await github.rest.checks.create({
              name: 'trivy-security-scan',
              head_sha: headSha,
              status: 'in_progress',
              details_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,  
              external_id: `${context.runId}`,           
              started_at: new Date().toISOString(),
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('check_run_id', checkRun.id);
            console.log("Created check");

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"
          # exit-code: "1"

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      # custom script to report scan results
      - name: Report scan results
        if: ${{ github.event.workflow_run != null}}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the head_sha from the workflow that triggered this one
            const headSha = context.payload.workflow_run.head_sha;

            // Get the head_sha from the workflow that triggered this one
            const headSha = context.payload.workflow_run.head_sha;

            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.create-check.outputs.check_run_id }},
              status: 'completed',
              output: {
                title: 'Trivy Security Scan Results',
                summary: `Scan completed!`
              },
              completed_at: new Date().toISOString(),
            });
            console.log("Updated check with conclusion!");
