name: Deploy to Staging Environment

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://justjio-staging.rowentey.xyz/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # only checkout the docker compose file
          sparse-checkout: |
            infra/docker-compose-staging.yml
          sparse-checkout-cone-mode: false

      # Create the .env file to use with docker-compose
      - name: Create .env file
        run: |
          cat << EOF > .env
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          KAFKA_HOST=${{ vars.KAFKA_HOST }}
          KAFKA_PORT=${{ vars.KAFKA_PORT }}
          POSTGRES_HOST=${{ vars.POSTGRES_HOST }}
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          VAPID_EMAIL=${{ secrets.ADMIN_EMAIL }}
          VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}
          SMTP2GO_API_KEY=${{ secrets.SMTP2GO_API_KEY }}
          CF_ACCESS_CLIENT_ID=${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET=${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          EOF

      # Transfer files to the server
      - name: Transfer files to staging server
        uses: RowenTey/cloudflared-scp-action@v1.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          port: ${{ secrets.SSH_PORT }}
          from: |
            ./infra/docker-compose-staging.yml
            ./.env
          to: ~/Documents/Codebase/justjio/
          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}

      # Rename docker-compose file on server and deploy
      - name: Rename and deploy on staging server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
          port: ${{ secrets.SSH_PORT }}
          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
          commands: |
            cd ~/Documents/Codebase/justjio
            docker compose down -v
            mv docker-compose-staging.yml docker-compose.yml
            docker compose pull
            docker compose up -d
            docker image prune -f
