name: Run Unit Tests

on:
  workflow_run:
    workflows: [Lint and Format]
    types:
      - completed
  workflow_dispatch:

jobs:
  test-api-server:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
          cache-dependency-path: server-api/go.sum

      - name: Install dependencies
        run: cd server-api && go mod download

      - name: Run unit tests
        id: test-step
        run: cd server-api && go test -v ./...

      - name: Report test results
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const conclusion = '${{ steps.test-step.outcome }}';

            // Only create check if we're in a PR context
            if (context.payload.pull_request) {
              await github.rest.checks.create({
                name: 'Unit Tests',
                head_sha: context.payload.pull_request.head.sha,
                status: 'completed',
                conclusion: conclusion,
                output: {
                  title: 'Unit Test Results',
                  summary: `Tests completed with status: ${conclusion}`
                }
              });
            } else {
              console.log('Not running in PR context, skipping check creation');
            }
