name: Run Unit Tests

on:
  workflow_run:
    workflows: [Lint and Format]
    types:
      - completed
  workflow_dispatch:

jobs:
  test-server-api:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
          cache-dependency-path: server-api/go.sum

      - name: Install dependencies
        run: cd server-api && go mod download

      - name: Run unit tests
        run: cd server-api && go test -v ./...
